{% set version = "0.3.8" %}

package:
  name: etuples
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/e/etuples/etuples-{{ version }}.tar.gz
  sha256: babb99e09428e7985d2baf5537f38ca1e47b596e1fadbef7db12388cab0a92de

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - etuples
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/pythological/etuples
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python S-expression emulation using tuple-like objects.
  description: |
    Python S-expression emulation using tuple-like objects.
  dev_url: https://github.com/pythological/etuples
  doc_url: https://github.com/pythological/etuples

extra:
  recipe-maintainers:
    - brandonwillard
