{% set version = "0.3.9" %}

package:
  name: etuples
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/e/etuples/etuples-{{ version }}.tar.gz
  sha256: a474e586683d8ba8d842ba29305005ceed1c08371a4b4b0e0e232527137e5ea3

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - cons
    - multipledispatch

test:
  imports:
    - etuples
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/pythological/etuples
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python S-expression emulation using tuple-like objects.
  description: |
    Python S-expression emulation using tuple-like objects.
  dev_url: https://github.com/pythological/etuples
  doc_url: https://github.com/pythological/etuples

extra:
  recipe-maintainers:
    - brandonwillard
