{% set version = "0.3.6" %}

package:
  name: etuples
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/e/etuples/etuples-{{ version }}.tar.gz
  sha256: ebd46ff6484201d6d1696f8ca95a481b0d26e485dd9bc211ba38b5cad9fcc8c2
  patches:

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - python >=3.6
    - cons
    - multipledispatch

test:
  imports:
    - etuples

about:
  home: https://github.com/pythological/etuples
  license: Apache-2.0
  summary: Python S-expression emulation using tuple-like objects.
  license_file: LICENSE
  dev_url: https://github.com/pythological/etuples

extra:
  recipe-maintainers:
    - brandonwillard
