{% set version = "0.3.4" %}

package:
  name: etuples
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/e/etuples/etuples-{{ version }}.tar.gz
  sha256: 98051379bd284ce462d868e44c389a22206b35c495ced259041af1f32a54a0a3
  patches:

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - python >=3.6
    - cons
    - multipledispatch

test:
  imports:
    - etuples

about:
  home: https://github.com/pythological/etuples
  license: Apache-2.0
  summary: Python S-expression emulation using tuple-like objects.
  license_file: LICENSE
  dev_url: https://github.com/pythological/etuples

extra:
  recipe-maintainers:
    - brandonwillard
